from . import student
from . import batch
from . import program
from . import department
from . import course
from . import classes
from . import faculty
from . import tt_data
from . import time_table